# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_auto_20180527_1105'),
        ('instalaciones', '0002_auto_20180527_1719'),
        ('materiales', '0002_material_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.FloatField()),
                ('iva', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.Instalacion')),
                ('materiales', models.ManyToManyField(through='pedidos.DetallePedido', to='materiales.Material')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido'),
        ),
    ]
