# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_pat', models.CharField(max_length=50)),
                ('apellido_mat', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('delegacion', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('codpost', models.CharField(max_length=50)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puestos.Puesto')),
            ],
        ),
    ]
