# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('num_empleado', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número de Empleado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia')),
                ('delegacion', models.CharField(max_length=50, verbose_name='Delegación')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('codigo_postal', models.CharField(max_length=50, verbose_name='Código Postal')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puestos.Puesto')),
            ],
            options={
                'ordering': ['num_empleado'],
            },
        ),
    ]
