# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('num_empleado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('puesto', models.CharField(choices=[('1', 'Puesto 1'), ('2', 'Puesto 2'), ('3', 'Puesto 3')], max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('delegacion', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['num_empleado'],
            },
        ),
    ]
