# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='calle',
            field=models.CharField(max_length=50, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo_postal',
            field=models.CharField(max_length=50, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='colonia',
            field=models.CharField(max_length=50, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='delegacion',
            field=models.CharField(max_length=50, verbose_name='Delegación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='municipio',
            field=models.CharField(max_length=50, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='num_empleado',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número de Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('1', 'Puesto 1'), ('2', 'Puesto 2'), ('3', 'Puesto 3')], max_length=50, verbose_name='Puesto'),
        ),
    ]
