# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('folio_compra', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_fk_probeveedor', models.ForeingKey(Proveedor, null=True, blank=False, on_delete=models.CASCADE)),
                ('total', models.IntegerField()),
                ('iva_compra', models.IntegerField()),
            ],
        ),
    ]
