# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('iva_compra', models.IntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('nombre_material', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_material', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('folio_compra', models.ManyToManyField(to='compras.Compra')),
                ('id_material', models.ManyToManyField(to='materiales.Material')),
            ],
        ),
    ]
