# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('instalacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('colonia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('numero_piso', models.CharField(max_length=50)),
                ('numero_instal', models.CharField(max_length=50)),
                ('fecha_instal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Material_instalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.Instalacion')),
            ],
        ),
    ]
