# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_auto_20180527_1105'),
        ('usuarios_departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('numero_piso', models.CharField(max_length=50)),
                ('fecha_instalacion', models.DateField()),
                ('hora_instalacion', models.TimeField()),
                ('empleados', models.ManyToManyField(to='empleados.Empleado')),
                ('usuario_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_departamentos.UsuarioDepartamento')),
            ],
        ),
    ]
