# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20180527_1105'),
        ('usuarios_departamentos', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_instalacion',
            name='instalacion',
        ),
        migrations.RenameField(
            model_name='instalacion',
            old_name='numero_instal',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='instalacion',
            old_name='fecha_instal',
            new_name='fecha_instalacion',
        ),
        migrations.RenameField(
            model_name='instalacion',
            old_name='instalacion',
            new_name='id',
        ),
        migrations.AddField(
            model_name='instalacion',
            name='empleados',
            field=models.ManyToManyField(to='empleados.Empleado'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='usuario_departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios_departamentos.UsuarioDepartamento'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Material_instalacion',
        ),
    ]
