# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacion',
            old_name='fecha_instalacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='instalacion',
            old_name='hora_instalacion',
            new_name='hora',
        ),
    ]
