# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDepartamento',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='RFC')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno'],
            },
        ),
    ]
