# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='estatus_pedido',
        ),
    ]
