# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
